
# 訓練相關參數 
training:
  lr: 0.0001           # 學習率 (1e-4)
  weight-decay: 0.0001   
  bs: 16               
  scheduler: 'steplr'    # StepLR 排程器
  gamma: 0.1           # 每次衰減乘以 0.1
  step-size: 10        # 每 10 個 epoch 衰減一次
  frames-per-video: 30

# 模型相關參數  
model:
  image-size: 299
  num-classes: 1
  depth: 2              
  dropout: 0.20         

  # S-Branch 
  s-branch:
    patch-size: 2
    cnn_channels: 2048
    dim: 256
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 512

  # L-Branch 
  l-branch:
    patch-size: 4
    cnn_channels: 256
    dim: 384
    depth: 2
    heads: 8
    dim_head: 64
    mlp_dim: 768
  
  # Cross-Attention Transformer 
  cross-attention:
    depth: 2
    heads: 8
    dim_head: 64